### PR TITLE
translated kotlin files to English

### PR DESCRIPTION
**Pull request by Upendrafalak**
Translated:

ExponenciacaoRecursiva.kt --> RecursiveExponentiation.kt
Fibonacci.kt --> Fibonacci.kt
Fatorial.kt --> Factorial.kt

Solution for Issue #190

### CODE REVIEW

**Review by kelvins — COMMENTED** [review]
Hi @Upendrafalak, thanks for the contrib, could you please fix the CI steps (link and lint checker)?

**Comment by Upendrafalak** [comment]
I have updated the code. Please check it and let me know if there are any further changes required. Thanks!

**Comment by ricardocarva** [comment]
Hi, @Upendrafalak. It looks like there is still something to be fixed. Can you please check the Lint checker and fix the issues?

**Comment by Upendrafalak** [comment]
Hi @ricardocarva, I have formatted the code as per the requirements. Please check!!

**Review by kelvins — APPROVED** [review]

**Pull request merged**
